services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: people-flow-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: people_flow_db
      POSTGRES_USER: people_flow_user
      POSTGRES_PASSWORD: people_flow_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - people-flow-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U people_flow_user -d people_flow_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
    driver: local

networks:
  people-flow-network-dev:
    driver: bridge 