package com.vilelatech.rh.domain.model.enums;

public enum TipoDocumento {
    RG,
    CPF,
    TITULO_ELEITOR,
    CERTIDAO_NASCIMENTO,
    CERTIDAO_CASAMENTO,
    CARTEIRA_TRABALHO,
    COMPROVANTE_RESIDENCIA,
    CERTIFICADO_ESCOLARIDADE,
    DIPLOMA,
    CERTIFICADO_CURSO,
    EXAME_MEDICO,
    ATESTADO_SAUDE,
    DECLARACAO_BANCARIA,
    CONTRATO_TRABALHO,
    TERMO_ADESAO,
    OUTROS
} 